import Modal from './components/Modal'
import './globals.css'
import type { PropsWithChildren } from 'react'

export const metadata = {
  title: 'Streamer Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-blue-100 via-blue-300 to-blue-500">
        {children}
        <Modal />
      </body>
    </html>
  )
}
