import Modal from './components/Modal'
import './globals.css'
import type { PropsWithChildren } from 'react'

export const metadata = {
  title: 'Streamer Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-gray-800">
      <body>
        {children}
        <Modal />
      </body>
    </html>
  )
}
